#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

#=================================================
# INSTALL APP
#=================================================
ynh_script_progression "Installing the app..."

pushd "$install_dir"
  ynh_hide_warnings ynh_exec_as_app npm install

  ynh_replace_regex --match="baseUrl: '.*'," --replace="baseUrl: '$(ynh_normalize_url_path $path)'," --file=texlyre.config.ts

  ynh_hide_warnings ynh_exec_as_app npm run build:prod
popd

chown $app:www-data $install_dir
chown $app:www-data -R $install_dir/dist

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"